import { Roboto } from "next/font/google";
import "./globals.css";
import Navegacion from "@/components/Navegacion";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='es'>
      <body className={roboto.className}>
        <header className='bg-slate-600 py-6 px-5 md:py-6 md:px-14'>
          <Navegacion />
        </header>
        <main className="container mx-auto py-7 px-6">{children}</main>
      </body>
    </html>
  );
}
